name: Deploy Glucoheart

on:
  push:
    branches:
      - test # ganti sesuai branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Build Backend
        working-directory: ./backend
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Build Admin
        working-directory: ./admin
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy Admin
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./admin/.next ./admin/public ./admin/package.json \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/glucoheart/admin/

      - name: Deploy Backend
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./backend/dist ./backend/package.json \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/glucoheart/backend/

      - name: Install deps & Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            export PATH=$HOME/.nvm/versions/node/v22.13.0/bin:$PATH

            cd /var/www/glucoheart/admin
            pnpm install --prod
            pm2 restart glucoheart-admin || pm2 start "pnpm start" --name glucoheart-admin --interpreter $(which node)

            cd /var/www/glucoheart/backend
            pnpm install --prod
            pm2 restart glucoheart-backend || pm2 start "pnpm start" --name glucoheart-backend --interpreter $(which node)
